-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Apr 19, 2012 at 12:57 AM
-- Server version: 5.5.22
-- PHP Version: 5.3.10-1ubuntu3

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `ispa`
--

-- --------------------------------------------------------

--
-- Table structure for table `projects`
--

CREATE TABLE IF NOT EXISTS `projects` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `department` varchar(40) NOT NULL,
  `prof_name` varchar(100) NOT NULL,
  `project_title` varchar(400) NOT NULL,
  `project_description` text NOT NULL,
  `eligibility_criteria` varchar(500) NOT NULL,
  `duration` varchar(400) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=133 ;

--
-- Dumping data for table `projects`
--

INSERT INTO `projects` (`id`, `department`, `prof_name`, `project_title`, `project_description`, `eligibility_criteria`, `duration`) VALUES
(1, 'EE', 'M B Patil', 'Developing Xenon board ( similar to FPGA Deo Nano, Krypton)', 'This project will involve development of a new board similar to that of FPGA and Krypton  boards.                        \r\nThe board is almost ready, some small issues with memory interfacing need to be sorted ou\r\nStudents are required to help in the memory interfacing, develop some good applications and exercises for the usage of the board. Like warm up experiments demonstrating the basic usage of LCD, hex pad etc           with FPGA. Documentation of all those is also a crucial part. Also students will be trying out XYLINGS (a programminginterface similar to ALTERA)', 'Sophies with at least a ''BB'' (8) in both Digital lab as well as the course (EE224).', '2 Months'),
(2, 'EE', 'M B Patil', 'Development of micro-controller platform:', 'Description: The project involves developing our own platform for the use of micro-controller 89C5132 (from ATMEL) similar to that  of the micro-controller 8085 (used in 3rd year). This would include making the processor USB-programmable and self content.  (i.e. to make power from USB is sufficient to most of the actions performed by it).', 'Sophies with at least a ''BB'' (8) in both Digital lab as well as the course (EE224).', '2 Months'),
(3, 'EE', 'M B Patil', 'Development of applications using PIC platform', 'The platfrom is almost ready. Students are required to make different applications using the platform.', ' Sophies with at least a ''BB'' (8) in both Digital lab as well as the course (EE224).', '2 Months'),
(4, 'EE', 'M B Patil', 'ARM/DSP based micro-controller development', '', 'Sophies with at least a ''BB'' (8) in both Digital lab as well as the course (EE224).', '2 Months'),
(5, 'EE', 'Madhu Belur', 'FOSSEE textbook companion ', 'Details of the FOSSEE textbook companion  project and the internship aspect can be found at\r\n http://www.scilab.in/Textbook_Companion_Project\r\n Please go through the website and read carefully  the procedure for the internship.\r\n\r\nThe procedure described there is for non-IIT students.\r\nFor IIT students, we won''t have a teacher. You can leave\r\nthat blank when proposing. (The amount is still 10k per book.)', 'Stipend: 10k per book', ''),
(6, 'EE', 'Siva Rama Krishna', '.Inductor Modeling and Desing in CMOS Technology', 'Involves inductor modeling design and analysis in standard cmos (umc 90nm) process for high speed applications.\r\n', ' Good at first year electricity and magnetism stuff', '2 Months'),
(7, 'EE', 'Girish Kumar', '', 'Projects vary\r\nfrom Web design, e-commerce, various RF circuits, radiation measurement\r\nat various places alongwith NGO and hospitals, and so on.\r\nProject can start anytime between May 1st and July 31st, 2012.\r\nProject wiil be allocated based on student''s interest and dedication.', 'Any student from first, second or third year', ''),
(8, 'EE', 'V M Gadre', 'Novel approaches to chirp detection - further methods', 'This involves detection and\r\ncharacterization of signals whose instantaneous frequency changes with\r\ntime, with minimal sampling/ observations. Note: in addition to working on\r\nthe project, the student will have to help out in the creation of some\r\neducational course material for NPTEL and carry out a literature survey on\r\na given theme.', 'Anyone who has done a course in Signals and Systems(Actual students to be selected after an Interview)', 'Major part of summers. Dates are flexible.'),
(9, 'EE', 'V M Gadre', 'Signal Characterization', 'To study the Fractional Fourier Transform and its possilbe application in chirp signal characterization The student(s) will work as a team with M.Tech/DD and PhD students who are working on the theme of signal characterization.', '1.Knowledge and special interest in Signals n Systems 2.No. of students working on this project: 1 or 2', 'flexible,shall be decided during the interviews '),
(10, 'EE', 'Maryam Shojaei', 'Internship projects on analog, mixed-signal and RF system design for healthcare applications', 'Smart healthcare technologies demand\r\nhigh-performance, reliable and low-power performance. The entire chain\r\nfrom sensor to network and power management demand solutions compatible\r\nwith the requirements of such autonomous and intelligent systems. This\r\ninternship program involves students in small system design, prototyping\r\nand test projects related to these areas.', 'CPI >9.00 Number of students: any number as long as CPI condition is satisfied. No specific prerequisite since students are from IIT-Bombay. Students from any batch can apply.', '2 months (1.5 months if student would like to put extra efforts to finish the project in 1.5 months).'),
(11, 'CHE', 'Rochish Thaokar', 'Rayleigh instability of charged drops in a microfluidic device', 'This is to demonstrate that the Rayleigh instability of a charged droplet can be observed using a simple technique of\r\nintroducing a highly charged drop into an insulated microfluidic channel and observe the same with time.  Conventional techniques use\r\nhighly sophisticated quadrupole setups for the same, with severe problems of immobilising the drops and dealing with fast dynamics. The\r\nmethod suggested proposes to circumvent this problem using physical confinement.', 'BTech Chemical Engg, Engg Physics', 'One month'),
(12, 'CHEM', 'C P Rao ', 'Metaloproteins, chemical sensors, protein drug interactions, metalation of proteins, DFT computations, molecular dynamics. ', 'Metaloproteins, chemical sensors, protein drug interactions, metalation of proteins, DFT computations, molecular dynamics.\r\n', 'Depending on Interest 1 or 2, Any body having long term interest is encouraged  Selections based on Interview by professor ', 'Can associate for short period,though long term is desirable. '),
(13, 'CHEM', 'P Ghosh ', 'Study mechanism of transition metal radiator catalysts with the aid of synthesis and computational methods. ', 'Involve students probing, investigating, a particular mechanistic pathway with the aim of identifying the reactive intermediate. In this regard a series of computational and experimental study would be undertaken. ', 'Any year . Selection based on CPI', '2-3 months '),
(14, 'CHEM', 'D Maiti ', 'Metal mediated synthetic transformations ', 'Metal mediated synthetic transformations\r\n', '2nd year. Selection based on Interview by professor ', '2-3 months '),
(15, 'CHEM', 'Anindya Dutta', 'Development of  software for fitting spectroscopic data', 'The student will be required to develop software for deconvolution of\r\nsepctral data into their components.', ' Both 1st and 2nd Year. A good knowledge of a suitable programming language is essential for this project.', 'Two months. Starting date can be as per convenience of the students.'),
(16, 'CHEM', 'S. N. Datta', 'Theoretical Investigation of the Origin of Magnetism in Molecules, Molecular Magnets, and Ferro-magnetic and Anti-Ferro-magnetic Molecular Crystals', 'The work mainly involves modeling of molecules, polymers and crystals containing radicals and study of their magnetic, magneto-optic or magneto-electronic properties using Quantum Mechanical program codes. The program-suites to be used are Gauss-View for modeling and Gaussian 03/09 and Crystal-09 for calculations.', ' Any year. Good academic records, completed First year with CPI above 8.0.', '2 months.'),
(17, 'CHEM', 'S. N. Datta', ' Investigation of the Biomolecules Involved In Redox and Enzymatic Process – A Theoretical Approach.', 'This work involves modeling of Biological active sites mainly enzymatic and their property verification using various program suite involving Melecular dynamics/Monte-Carlo and Quantum Mechanics and static and dynamic Electrostatic calculations. The program-suites to be used are Gauss-View, Hyper-Chem, Viewerlite, SwissPdbViewer etc for modeling and Hyper-Chem (for Melecular dynamics/Monte-Carlo), Gaussian and Molcas (for Quantum Mechanics), Delphi and MCCE (for static and dynamic Electrostatic respectively) calculations.\r\n', 'Any Year Good academic records, completed First year with CPI above 8.0.', '2 months.'),
(18, 'CHEM', 'K.P. Kaliappan', 'Organic synthesis', 'Initial exposure to organic chemistry, synthesis of organic compounds.', '1, 2nd year. CPI above 7 ', '2-3 months'),
(19, 'EE', 'Virendra Sule', 'Development of a software library implementation for Boolean representation of equations over binary extension fields', 'In several applications such as cryptology polynomial\r\nequations arise which are expressed in terms of arithmetic in binary\r\nextension fields. In order to solve such equations one can utilize methods\r\nof solving Boolean equations over Boolean algebras. However application of\r\nthese methods first requires representation of the original equation in\r\nthe Boolean form. This library is aimed at achieving this representation.\r\n\r\nWork description: Understanding the arithmetic of binary extension fields,\r\nformulate representation of field equations and Boolean equations in\r\nsuitable data structures, implement the library to convert objects from\r\none data structure to another. The task can be accomplished either in\r\nC/C++ or Python/Java. (Python may be easiest to work with).', 'Minimum 3rd year student. No cut off prereq.', ''),
(20, 'EE', 'B.M.Arora ', 'Development of a device for automatic measurement of I vs V characteristics of a Solar Cell with rating of a few watts. ', 'Minimum CPI of 8.Also the student should be familiar with micro-controller coding. CPI would not matter if the student is well experienced with micro-controller coding\r\n', '', ''),
(21, 'EE', 'Dilawar Singh(Guide: Prof Sachin B Patkar) ', 'Logic simulation on many-core hardware ', 'Student(s) is(are) expected to write digital logic description in C/C++.\r\n\r\nThese programs are to be simulated over many-core hardware. We''ll use\r\neither nvidia-CUDA or some multi-threading libraries. When multiple tasks\r\n(not necessarily balanced) are scheduled in parallel, the challenge is to\r\ncome up with an efficient design to synchronizing them. We wish to\r\nbuild a small collection of such programs which can be tested on many-core processors."\r\n', 'Student MUST have strong C/C++ skills with a grip over data-structures.      Students who have coded with multi-threaded libraries will be preferred.       CPI : Either > 8.0 grade in programming courses or good project done in      c/c++. Overall CPI is not an issue. Please send your project-code along with      application.  Time duration :      A two months stay in campus.', '2 months'),
(22, 'EE', 'Sibiraj Pillai ', 'Establishing a digital communication link. ', '', 'Should be a thirdie..  ', ''),
(23, 'EE', 'S V Kulkarni ', 'Modeling of magnetic hysteresis', 'Magnetic circuit of a transformer, made from steel laminations, exhibits nonlinear and hysteretic characteristics. A precise mathematical model should consider these characteristics. Some major challenges associated with any formulation dealing with the problem are convergence issues and high computational time. The project involves the measurement of hysteresis loop of the core materials using Epstein tester. The measured hysteresis loop can be linearlized mathematically using a complex permeability approach. The approach can be useful in assessing the performance of the magnetic circuit and/or in diagnosing its condition\r\n', '', '"Eligibility Criteria:2nd or 3rd year, CPI>8.0  Duration:2 months (May 1st week/2nd week onwards)" '),
(24, 'EE', 'Neeraj Panwar(Prof. Udayan Ganguly) ', 'ReRAM(Resistive Random Access Memory)', 'Work Description:\r\n1)Fabrication - of devices in Nanofabrication lab\r\n2) Material Characterization - of the deposited thin films (like thickness, refractive index, uniformity,\r\nsmoothness, grain size, phase, composition, stoichiometry, SEM imaging etc.) in Fabrication lab\r\n3)Electrical Characterization - of the devices \r\n4)simulate the quantum mechanical tunneling problem in MOS (Metal-Oxide-Semiconductor)\r\nby writing a code in Matlab or in Sentaures.\r\n', '3rd year student is preferred, but 2nd or 1st year students can also apply.  No. of Students: 2', ''),
(25, 'EE', 'S P Dutta Gupta ', 'Optimization of Energy Systems using wireless sensor networks ', '', 'Long term commitment required', ''),
(26, 'EE', 'Vishal (RA) Prof:B G Fernandes', 'Study Project on "estimation and reliability of any given power circuit', 'Students will have to go through IEEE papers and find out some things on internet.', 'Eligibility Criteria:none  No.of students:1  Prerequisites:none, just interest matters', ''),
(27, 'MET', 'Gururajan', 'MUSE: software development', 'I have a phase field code written in C which can do microstructural evolution in elastically stressed solids. I want to make a front end for the code so that the program can be shipped as a free openware.', 'Good programming skills', '1 month (mid June to mid July)'),
(28, 'MET', 'Gururajan', 'Coding with CUDA', 'I am looking for somebody who will write codes using CUDA for simple problems and benchmark the performance of GPU based machines for scientific computations. If it is established that CUDA does give better performance, I want the student to port a code written in C/C++ to CUDA and run the same for larger systems (do 2D calculations by extending the existing 1D code). If the student manages to port the existing 1D code for snow microstructural evolution, I will be able to pay an honararium (of the order of 10-25K depending on the work completed)', 'Good programming skills and the willingness to learn CUDA; fairly independent student who can work even in my absence  ', 'early May to mid July'),
(29, 'MET', 'A. Panwar', 'Molecular Dynamics on GPU ', 'Use the CUDA implementation of LAMMPS to test on GPUs & compare performance with parallel code on multi-core CPU', 'Good programming skills', '2 months'),
(30, 'MET', 'A. Panwar', 'Langevin Dynamics Simulation of Polymer stretching: effect of bending energy', 'Explore the effect of bending energy on the single molecule response to a stretching force', '', '2 months'),
(31, 'MEMS', 'D. Bahadur', 'Targeted drug delivery using magnetic nanoparticles', 'Magnetic nanoparticles can be encapsulated in suitable biocompatible polymer with cancer drug. Drug delivery would be done by change in pH and temperature', '', '2 months'),
(32, 'EE', 'Preeti Rao', 'Recording and classification of musical instrument sounds', '', 'Background required: good in DSP theory, excellent C programming Note: open to 3rd year students only', ''),
(33, 'EE', 'Subhashish Chaudari', 'Open contest for Development of Client End Biometric Extractor', 'details in http://uidai.gov.in/images/FrontPageUpdates/biometric_sdk_challenge_28march.pdf', 'Eligibility Criteria:none', ''),
(34, 'EE', 'Ramgopal Rao', 'Building a self powered wireless sensor node for explosive detection for Mumbai trains/buses.The work will involve hardware/software co-design with power generated  from train/bus vibrations using a piezoelectric energy scavenging device. ', 'Building a self powered wireless sensor node for explosive detection for Mumbai trains/buses.The work will involve hardware/software co-design with power generated \r\nfrom train/bus vibrations using a piezoelectric energy scavenging device. ', 'both 2nd and 3rd year students(2 students for this project)', ''),
(35, 'EE', 'Ramgopal Rao', 'Stand-off detection for explosive vapours using a vehicle mounted  cantilever sensor and video transmission. The system will be used for  tracking explosives in unidentified bags', 'Stand-off detection for explosive vapours using a vehicle mounted \r\ncantilever sensor and video transmission. The system will be used for \r\ntracking explosives in unidentified bags', 'both 2nd and 3rd year students(2 students for this project)', ''),
(36, 'CHE', 'A.K. Suresh', 'Mathematical models for the number and distribution of contact points in a random packing of spheres', 'In reactions between particulate solids, the reaction begins at the points where the reactant particles touch each other, and then proceeds into one or both reacting particles. The number of such points of contact when particles are randomly mixed and reacted is therefore an essential input to any model of the reaction itself. In this project the student will study the models in the literature (mostly of a stochastic nature) for modeling particle-particle contact in random packings, Based on the study, extensions of the models to generate distributions of contact points or even new models are to be attempted', 'Good familiarity with I year level mathematics; probability and statistics, statistical distributions. A flair/inclination for analytical reasoning and math modeling is essential', '8-10 weeks, starting I week of May.'),
(37, 'CHE', 'Santosh Noronha', 'Project 1', 'Virtual Labs aims to move all the lab experiments to your web browser . This way the experiments could be accessed remotely from any part of the world with almost zero cost. This project is funded by Ministry of Human Resource  Development (MHRD). It involves developing simulators using Free and Open Source Tools/Softwares for core Chemical Engineering related experiments. To know more about Virtual Labs, visit: http://vlab.co.in/\r\nYou can see the already developed Virtual Labs related to Chemical Engineering by our team at IIT Bombay by visiting the following website: http://iitb.vlab.co.in/?sub=8&brch=116 \r\n\r\n(i) Identifying theory and developing storyboards:\r\nStoryboard represents the step by step procedure to be followed to carry out the experiment in the virtual lab. Each slide in the storyboard gives a screenshots as visible to the user of the experiment\r\nFor developing storyboards, you need to first identify the concept from the theory courses done by you for which you are going to develop a Virtual Labs experiment. Theory documented during the storyboard development will be helpful during backend/frontend coding.\r\n(ii) Developing backend codes for the theory in Scilab/PHP/python/C++ etc: This task involves writing codes for executing the experiment eg. solving relevant equations etc. in Scilab\r\n(iii) Developing frontend codes (php, javascript, mysql): This task involves writing codes, mainly in PHP, javascript, mysql etc. to develop the interface for conducting virtual lab experiment\r\n', 'No restriction', '2 months'),
(38, 'CHE', 'Santosh Noronha', 'Project 2', '\r\nVirtual Labs aims to move all the lab experiments to your web browser . This way the experiments could be accessed remotely from any part of the world with almost zero cost. This project is funded by Ministry of Human Resource  Development (MHRD). It involves developing simulators using Free and Open Source Tools/Softwares for core Chemical Engineering related experiments. To know more about Virtual Labs, visit: http://vlab.co.in/\r\nYou can see the already developed Virtual Labs related to Chemical Engineering by our team at IIT Bombay by visiting the following website: http://iitb.vlab.co.in/?sub=8&brch=116 \r\n\r\nYou can also develop a virtual labs experiment for hardware based remote triggered experiments which too involves the above 3 tasks. Prof. Noronha has two hardware experiment on which you can work as part of the Virtual Labs summer projects. These are:\r\nBioreactor: This bioreactor is basically a stirred tank reactor with output parameters such as Oxygen content & pH and input parameters to be monitored as speed of rotation, air flowrate etc.You need to design experiments making use of this reactor. You will be working on a bioreactor setup kept in his lab, of course, without any biological aspects like microorganisms etc.\r\nMicrofluidics: Microfluidics deal with fluid flow through channels with very minute dimensions. You can design and carry out experiments on the setup using simple fluids. Broad application of these devices will be for eg. diagnostic kits to be used in rural areas for testing blood samples. If you want to know more about this research field:  http://www.stanford.edu/group/foundry/\r\n\r\nThrough these summer projects our aim is to develop close to 50 storyboards involving the concepts taught in the 5 chemical engineering theory courses as a part of 2nd year curriculum.', '2 students per hardware experiment', ''),
(39, 'CSE', 'Supratik Chakraborty', 'QBF-SAT solving', 'QBF-SAT refers to the problem of determining if a quantified Boolean formula\r\nis satisfiable (see www.qbflib.org for related information).  We have\r\nbeen working\r\non a couple of new strategies for QBF-SAT, and have prototype solvers\r\nrunning.\r\nThis summer project will involve understanding our approach vis-a-vis other\r\napproaches, identifying opportunities for algorithmic/data-structure\r\noptimizations\r\nin our approach, implementing these ideas in our existing code-base, and\r\nevaluating their performance on real benchmarks.', 'Student positions available: 1-2 2nd or 3rd year student with excellent UG-level background in discrete structures, algorithms and data structures.  Those with a good background in algorithms will be given preference.  Excellent coding, development, debugging skills as demonstrated by executed projects is also a must. CPI above 8.5 is desired, but I am willing to consider students with less CPI if there is proven record of their competency in developing tools.', '2-2.5 months (mid-May to end July).'),
(40, 'CSE', 'Supratik Chakraborty', 'A Quantifier Elimination Tool for the Public Domain ', 'We have developed a new quantifier elimination algorithm (see the paper\r\n"A Quantifier Elimination Algorithm for Linear Modular Equations and\r\nDisequations" by\r\nA. John and S. Chakraborty, Proceedings of CAV 2011) and there is sufficient\r\ninterest from the research community in having an implementation of this\r\nas part\r\nof a public-domain package.  This project is about our ongoing effort in\r\nmaking our\r\ntool (implementing the above algorithm) get to a form that can be\r\nreleased in the\r\npublic domain.   There are some requirements and guidelines that need to\r\nbe followed\r\nto have the tool integrate and communicate with other public domain tools.\r\nSpecial emphasis must be given to tune the performance so that\r\nit scales to large examples (it already does, but we can do even better).\r\nThis project will require excellent coding, debugging, development skills,\r\nand a fairly good background in data structures.  Good background in\r\nalgorithms is\r\na plus, but not necessary.  As a bonus, the names of those participating\r\nin this\r\nproject will be listed in the public domain distribution when it is\r\neventually released.', 'Student positions available: 1-2  Eligibility criteria: 2nd or 3rd year student with excellent UG-level background in discrete structures, algorithms and data structures.  Those with a good background in algorithms will be given preference.  Excellent coding, development, debugging skills as demonstrated by executed projects is also a must. CPI above 8.5 is desired, but I am willing to consider students with less CPI if there is proven record of their competency in developing tools. ', '2-2.5 months (mid-May to end July).'),
(41, 'CIVIL', 'Subimal Ghosh', 'Data Driven Hydroclimatic Model', '1.) Use of Probability Statistical Approach  2.) Assessment of Impacts of Climate Change 3.) Hydrological Change Detection', '', ''),
(42, 'CIVIL', 'Prakash Nanathagopalan', '1.) Pervious Concrete  2.) High Strength Concrete', '1.) Experimental Investigations on the properties of pervious concrete 2.) Development of Mixture Design and investigations on properties', '2nd year : 1 ; 1st year :3', ''),
(43, 'CIVIL', 'Siddhartha Ghosh', 'Structural Mechanics; Fatigue loading; Vibrational Loading; Impact Loading (all would be involved)', 'Designing a cage for cage fishing in a reservoir (The topic is difficult to understand by the name, I can give a diagram explaining what is to be done)\r\nKnowledge of ETabs and SAP would be beneficial', '1)Third year student 2) Struct 1 and 2 ', ''),
(44, 'CIVIL', 'Balaji Ramakrishnan', 'Assessment of tidal current energy along coastal waters', '(i) Preliminary data collection, evaluation and identification of various engineering\r\nstudies need to be carried out for feasibility studies;\r\n(ii) Analysis of successful case studies;\r\n(iii) Analysis of conceptual options of tidal current power extraction devices.', '2nd Year / 3rd Year students of minimum cpi 8.5 ', ''),
(45, 'CIVIL', 'T I Eldho', 'Coastal hydrodynamics', 'Modelling and Programming will be there using some software', '1.) 2nd Year Student  2.) Min cpi of 7     3.)Good programming skills', ''),
(46, 'CIVIL', 'T I Eldho', 'scoring modelling bridge piers using fluent software', 'scoring modelling bridge piers using fluence software', '1.) 2nd Year Student  2.) Min cpi of 7 ', ''),
(47, 'CIVIL', 'V Jothiprakash', 'Chaotic analysis of rainfall', 'The participant would work under the professor for the first 15 days and shall be guided by a research scholar for the rest of the period.The amount and nature of work shall depend on the participant''s response.', 'CE401:-Water Resources Engineering OR CE669:- Physical and stochastic hydrology.', ''),
(48, 'CIVIL', 'D.M. Dewaikar', 'Active thrust on retaining wall under the combined effect of self weight and surcharge.', ' Develop tables and charts useful for computational purpose.', ' Students currently in their 3rd year, Soil Mechanics, Engg. Mechanics, Excel', ''),
(49, 'CIVIL', 'Ashish Juneja', 'Web based interactive virtual triaxial shear testing', 'Develop virtual laboratory experiment as supplement to the real CU and CD triaxial compression testing. This highly interactive multimedia package will help simulate very sophisticated and costly equipment. All information on the instrumentation, specimen preparation, assembly and testing will be provided on a single platform. In addition, the candidate will be required to prepare database of experimental data for test simulation. his will help to report the interpretation and errors associated with the measurement techniques.', 'Coding specially C/C++, Phython (should know)', ''),
(50, 'CIVIL', 'B.V.S.Viswanadham', '1.Studies on the use of grout mattress for slow protection works 2. Use of geophone for embanking construction on soft ground', '', 'Third year students CPI>=7', ''),
(51, 'CIVIL', 'B.V.S.Viswanadham', '1. Development of sand hopper for high gravity experiments 2. Design of pervious concrete', '', 'Second year students CPI>=7', ''),
(52, 'CIVIL', 'B S Pani', 'Diffusion of Jets', 'Fluid Mechanics, Hydraulic Engineering, FLUENT software\r\nNumerical Simulation using FLUENT', 'Open for 2nd and 3rd year', ''),
(53, 'CIVIL', 'M J Reddy', 'Risk analysis of floods & its use for design of hydraulic structures', 'Students will learn basic methods for estimation of hydrologic risks & its application to hydrologic design of hydraulic structures (eg. diversion canals), cross drainage structures(eg culverts and bridges) etc', 'Passed 4th sem. Min 8 SPI.. Done courses related to fluid mech n hydraulics.. Max 2 students', ''),
(54, 'ME', 'P. P. Date', 'Non-destructive method of measuring density variation :', 'Method of measuring \r\nvariation in density across the length of the product', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(55, 'ME', 'P.P Date', 'Measurement of particle size and shape', 'Powder particles have random shape & \r\nsize. Methods to calculate deviation from sphericity and particle size need to be \r\ndeveloped', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(56, 'ME', 'P.P Date', 'Measurement of pressure and flow velocity in injection moulding dies', 'Metal is \r\ninjected into dies (similar to casting process). The flow of material in the dies is \r\nnot visible. Measurements of pressure and velocity are to be taken', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(57, 'ME', 'P.P Date', 'Separation of metallic power from shopfloor waste', 'Design and fabrication of a \r\ndevice to isolate metallic powder from shopfloor grinding waste for green \r\nmanufacturing', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(58, 'ME ', 'P.P Date', 'Surface engineering of powders', 'Engineering surfaces of powder particles to that \r\nthey remain separate in moulding and come together in sintering.', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(59, 'ME', 'P.P Date', 'A fabric liner that would cool in summer, i.e., a cool vest/ cool shirt', 'An artificial \r\nfabric / liner that cools cool in summer and warms up in winter', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(60, 'ME', 'P.P Date', 'A device to measure the angle of bend', 'Angle of bend in bent products must be \r\nmeasured accurately. A device to do so needs to be designed & fabricated', 'Students must generate different approaches (using known principles of physics and  chemistry) to perform the functions listed above. Following this, they should select a few  and conceptualise the design(s) of their devices and sketch/draw them. Some calculations  may be performed based on preparedness in Strength of materials and solid mechanics. Deliverables include design and drawing of the devices conceptualized from the  viewpoint of manufacturing them and taking trials. Fabrication shoul ', ''),
(61, 'ME', 'M V Rane ', 'Solar Refrigerator / Water Heater ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(62, 'ME', 'M V Rane ', 'Radiant Cooling Panels ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(63, 'ME', 'M V Rane ', 'Plastic air to air heat exchange ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(64, 'ME', 'M V Rane ', 'Solar Air Conditioning ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(65, 'ME', 'M V Rane ', 'Improving performance of household refregirators ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(66, 'ME', 'M V Rane ', 'Steam Expanders ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(67, 'ME', 'M V Rane ', 'Consenser heat recovery for desalination ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(68, 'ME', 'M V Rane ', 'Hybrid air cooling ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(69, 'ME', 'M V Rane ', 'Plastic Solar Air heaters ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(70, 'ME', 'M V Rane', 'Solar thermoelectric co-generation ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(71, 'ME', 'M V Rane', 'Pulsating heat pipes ', '', 'Hardwork, regularity and sincerity. Also, wants to meet the students before handing out any projects. ', ''),
(72, 'ME', 'S V Prabhu ', 'Will tailor projects in fluid dynamics and heat transfer, according to student interests  ', '', 'Sincerity, also, selection on one to one interaction with the Prof.  ', ''),
(73, 'ME', 'P S Gandhi ', 'Nonlinear Dynamical Systems and Control, Mechatronics ', '', 'He is looking for long term commitment. Plus the other conditions like sincerity etc apply here too. ', ''),
(74, 'ME', 'P S Gandhi', 'Micro Electromechanical Systems (MEMS) ', '', 'He is looking for long term commitment. Plus the other conditions like sincerity etc apply here too. ', ''),
(75, 'ME', 'P S Gandhi ', 'Robotic systems, kinematics and dynamics ', '', 'He is looking for long term commitment. Plus the other conditions like sincerity etc apply here too. ', ''),
(76, 'ME', 'K P Karunakaran ', 'Computer Numerical Control ', '', 'He needs good students to work under him, and is even ready to hand out handsome stipend amounts ', ''),
(77, 'ME', 'K P Karunakaran ', 'Rapid Prototyping & Tooling ', '', 'He needs good students to work under him, and is even ready to hand out handsome stipend amounts ', ''),
(78, 'ME', 'K P Karunakaran ', 'Computer Graphics ', '', 'He needs good students to work under him, and is even ready to hand out handsome stipend amounts ', ''),
(79, 'CHE', 'Kannan Moudgalya', 'Spoken Tutorials', 'Sir is looking for people to create spoken tutorials in many open source software systems, in science, engineering, commerce and IT. Some examples of software that is of interest to engineers are gnuplot, xfig, scilab, inkscape, ASCEND, cell-designer, modeller, openfoam, gns3, nmap and sumo. Some examples of IT are various utilities in linux, such as bash, sed, emacs, SCIM, make, languages, development environments and content creation environments like Joomla and Drupal.  Almost ANY FOSS system is welcome.\r\n\r\nIt is possible to work in groups also. Professor also gives a decent honorarium, based on the deliverables.\r\n\r\nThe details regarding the spoken tutorial are available in the following links.\r\nhttp://spoken-tutorial.org/CSI.pdf\r\nhttp://spoken-tutorial.org/What-is-a-Spoken-Tutorial-2-Minute-Video-English\r\nhttp://spoken-tutorial.org/What_is_a_Spoken_Tutorial_English\r\n', '', ''),
(80, 'PHY', 'Alok Shukla ', 'GPU computing', 'Graphical Processing Units (GPUs) are ideally suited for\r\nhigh-performance parallel computations, and considered to be far\r\nsuperior than traditional CPUs. In this project the student will have\r\nto read as much as possible about GPUs and then try to code simple\r\napplications using Fortran 90.', '', ''),
(81, 'PHY', 'Alok Shukla ', 'High-Performance Parallel Computing: ', 'In this project student will have to read about the basics of parallel\r\ncomputations using OpenMP and MPI. Then, if time permits, the student\r\nwill have to develop simple programs using OpenMP and MPI, employing\r\nFortran 90 language. Some knowledge of computer programming is\r\nassumed, however, Fortran 90 needed for the coding can be learnt very\r\nquickly.', '', ''),
(82, 'PHY', 'Pradeep Sarin', ' Construction of a Cosmic Ray particle detector', 'Broad area: Experimental Particle Physics\r\n\r\nProject details:\r\nIn this project we will build a multi-wire propostional chamber : a gas filled detector of approximate dimensions 2m height x 1m width x 0.1m depth with for the detection of tracks created by cosmic rays.\r\nSample videos of similar finished product is at:\r\nhttp://www.youtube.com/watch?v=0dX8OrCi2EE\r\nhttp://www.youtube.com/watch?v=hlhKVVzEd9E\r\nThe final detector will be permanently installed at the entrance of my research lab in Physics', 'I am looking for 3 1st year students + 2 2nd year students. They will be supervised by 1 fourth year student. The 2nd year students need to have completed at least Basic electronics + Analog electronics lab. All students must be familiar with electronic circuits either through curricular work or hobby activities. Students will be interviewed in person.', 'May 10 to July 20.'),
(83, 'PHY', 'Pradeep Sarin', ' Testing and programming the Aakash tablet PC', 'This project will involve writing code in Android OS API to run on the Aakash tablet. It is not clear yet whether I will offer this project. Depends on my other research plans for the summer and availability of sufficient number (~ 2-3) freshies+sophies skilled in systems programming and coding for Android OS.', '', ''),
(84, 'PHY', 'Kailash Rustagi', 'Studies in Quantum Technology', 'Quantum physics concepts play an important role in many of the devices now in use or being developed. The brief review “Quantum technology: the second quantum revolution” by Jonathan P. Dowling and Gerard J. Milburn,  Phil. Trans. R. Soc. Lond. A  15 August 2003   vol. 361, 1655-1674 (2011) gives a good idea of the broad areas covered. There are many possibilities to be explored. The idea is to make simple model calculations- using both analytical and numerical techniques to get first estimates of these possibilities. More specifically, I would be looking at optical properties of semiconductor nano-membranes and quantum dots. The “big” problem is divided into many do-able bits. ', 'Should be comfortable with first course on Quantum mechanics and generally happy doing theory.', 'Two months of intense reading followed by 5-6 hours per week most of year. Starting date any time but I will be away in June 2012. '),
(85, 'PHY', 'Avatar Tulsi', 'Generalizations of quantum search algorithm', 'first, i expect the students to read about quantum algorithms\r\nand then students can do some numerical calculations, they should know\r\nsome programming language for it. even if a student just want to learn\r\nabout quantum computing and quantum information, that is also fine with\r\nme', 'None', '2 months'),
(86, 'CSE', 'Prof. Puru and Prof Varsha Apte', 'Joint Projects', 'Please refer to https://docs.google.com/document/pub?id=1fdQeE83oQNYyGALvgCJACPJPsxtDJmkh2Rm0XvOxldU for further details', '', ''),
(87, 'AERO', 'Prof. Hablani ', 'ADCS of Pratham', 'ADCS of Pratham – a relook ; sun sensor measurement noise and commensurate weighing of measurements ;  orbit-averaged magnetic attitude control\r\n', 'Some proficiency with C++ and Matlab would be helpful.  ', ''),
(88, 'AERO', 'Prof. Hablani', 'Alignment Kalman filter ', 'Alignment Kalman filter\r\n', '', ''),
(89, 'AERO', 'Prof. Hablani', 'Applied dynamic programming for optimization of dynamical systems ', '', '', ''),
(90, 'AERO', 'Prof. Hablani', 'Genetic Algorithm based Star Camera Calibration using Star Maps ', '', '', ''),
(91, 'AERO', 'Prof. Hablani', 'Star tracker deblurring for attitude determination ', '', '', ''),
(92, 'AERO', 'Prof. Hablani', 'Missile radar gimbal controllers for air-to-air tracking ', '', '', ''),
(93, 'AERO', 'Prof. Hablani', 'Integrated aircraft navigation and tracking (track-while-scan) using INS, airborne radar, Doppler radar, synthetic aperture radar  ', '', '', ''),
(94, 'AERO', 'Prof. Hablani', 'Stellar Navigation of  land- and sea-based missiles ', '', '', ''),
(95, 'AERO', 'Prof. Hablani', 'Space-based and wide-area augmentation system-based air navigation for precise positioning ', '', '', ''),
(96, 'AERO', 'Prof. Hablani', 'Space-based and wide-area augmentation system-based air navigation for precise positioning ', '', '', ''),
(97, 'AERO', 'Prof. Hablani', 'GNSS (global navigation satellite systems) aided navigation and tracking ', '', '', ''),
(98, 'AERO', 'Prof. Hablani', 'GPS/INS integration: loosely-coupled, tightly-coupled, and deeply-integrated ', '', '', ''),
(99, 'AERO', 'Prof.Hablani', 'GAGAN – Geostationary Aided GPS Air Navigation plus microwave imaging for Category III landing algorithms ', '', '', ''),
(100, 'AERO', 'Prof. Hablani', 'IRNSS – Indian Regional Navigation Satellite System for air navigation, take-off and landing for Category III landing ', '', '', ''),
(101, 'AERO', 'Prof. Hablani', 'Navigation of a land vehicle in battlefield (Arjun tank)  ', '', '', ''),
(102, 'AERO', 'Prof. Hablani', 'Outdoor, indoor land Navigation with pseudolites ', '', '', ''),
(103, 'AERO', 'Prof. Hablani', 'Guidance and integrated IRNSS-INS navigation of precision guided munitions  ', '', '', ''),
(104, 'AERO', 'Prof. Hablani', 'Air-bearing table experiments to calibrate (determine error characteristics and performance of)  gyros and accelerometers and star trackers ', '', '', ''),
(105, 'AERO', 'Prof. Hablani', 'BrahMos supersonic missile guidance with multi-spectral scanner identifying maneuvering and non-maneuvering targets  in cluttered environments ', '', '', ''),
(106, 'AERO', 'Prof. Hablani', 'Agni Missiles – Guidance, Navigation and Control for maneuvering and non-maneuvering targets  ', '', '', ''),
(107, 'AERO', 'Prof. Hablani ', 'Midcourse and terminal guidance of missiles; three-, five-, and six-degree-of-freedom simulations ', '', '', ''),
(108, 'AERO', 'Prof. Hablani', 'Midcourse and terminal guidance of missiles; three-, five-, and six-degree-of-freedom simulations ', '', '', ''),
(109, 'AERO', 'Prof. Hablani', 'Laser beam pointing control, acquisition and tracking system  (for satellite or inter-satellite communication and directed energy weapon) ', '', '', ''),
(110, 'AERO', 'Prof. Hablani', 'Orbit establishment and attitude acquisition of satellites  ', '', '', ''),
(111, 'AERO', 'Prof. Hablani', 'Mathematical modeling, analysis and simulation of dynamics and control of coupled rigid and flexible components of spacecraft with time-varying configurations, subject to environmental forces ', '', '', ''),
(112, 'AERO', 'Prof. Hablani', 'Spacecraft attitude determination with magnetometers ', '', '', ''),
(113, 'AERO', 'Prof. Hablani', 'Spacecraft payload controllers: strip imaging motion and its control; off-nadir pointing of articulated antenna of geostationary satellites;  spot beam control; conical scan motion control ', '', '', ''),
(114, 'AERO', 'Prof. Hablani', 'Long-term formation control of collocated geostationary satellites along with station-keeping: modeling of relative orbital dynamics using synchronous elements, relative ranging, navigation, and control; assessment of nav errors ', '', '', ''),
(115, 'AERO', 'Prof. Hablani', 'Specialized orbits design for remote sensing satellites for designated ground coverage:  sun-synchronous, frozen orbits, repeat ground tracks, the so called Magic orbits; minimum altitude variation,  ', '', '', ''),
(116, 'AERO', 'Prof. Hablani', 'Remote sensing: 1)surveillance with synthetic aperture radar; imaging and processing 2)design of a fire satellite to sense fires; NASA Langley’s FireSat; Germany’s Bi-spectral Infra-Red Detection nanosatellite ', '', '', ''),
(117, 'AERO', 'Prof. Hablani', 'Lunar and interplanetary trajectories design accounting for sensor delay; deep space tracking and navigation of lunar and interplanetary spacecraft ', '', '', ''),
(118, 'AERO', 'Prof. Hablani', 'Chandrayan-II navigation, nav error analysis; attitude determination and control in lunar orbit ', '', '', ''),
(119, 'AERO', 'Prof.Hablani', 'Reusable launch vehicle ascent and reentry guidance, IRNSS-based navigation, and control; ', '', '', ''),
(120, 'AERO', 'Prof. Hablani', 'Image motion compensation for exo-atmospheric interceptors ', '', '', ''),
(121, 'AERO', 'Prof. Hablani', 'optimal slow maneuvers of multi-body flexible satellites with sun- tracking solar arrays, using CMGs and gravity gradient torque for de-saturation,  ', '', '', ''),
(122, 'AERO', 'Prof. Hablani', 'Multi-body deployment: RISAT radar antenna and other multi-body spacecraft deployments; accuracy of deployed configuration ', '', '', ''),
(123, 'AERO', 'Prof. Hablani', 'Determination of propellant mass in satellites from forced vibration and frequency identification ', '', '', ''),
(124, 'AERO', 'Prof. Hablani', 'Pointing control system for ISRO’s Astrosat ', '', '', ''),
(125, 'AERO', 'Prof. Hablani', 'Infra-structure and town planning with Cartosat-2B, with a resolution of 0.8 m  ', '', '', ''),
(126, 'AERO', 'Prof. Hablani', 'Deployment of solar arrays and antennas using Sim Mechanics ', '', '', ''),
(127, 'AERO', 'Prof. Hablani ', 'Guidance, navigation and control of flexible launch vehicles  ', '', '', ''),
(128, 'AERO', 'Prof. Hablani', 'Estimation of earth’s mass distribution from observations of relative distance between two tandem satellites ', '', '', ''),
(129, 'AERO', 'Prof. Hablani', 'Mobile Robotic control ', '', '', ''),
(130, 'AERO', 'Prof. Hablani', 'Train navigation with IRNSS  ', '', '', ''),
(131, 'AERO', 'Prof. Hablani', 'satellite tracking of ground and air targets ', '', '', ''),
(132, 'MET', 'Somnath Basu', 'Plasma Spray coatings for dental implants', 'Scope: Optimization of plasma spraying process parameters and powder characteristics for achieving consistent coatings. The coated components would eventually be used as dental or orthopedic implants.', '2 students are required', '');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
